name: skmultiflow-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - scikit-learn
  - pandas
  - matplotlib
  - ipympl
  - nodejs
  - pip:
    - scikit-multiflow
